{"uuid": "ff5d001a-fc7f-4756-9932-330aaa902ba1", "children": ["97868364-1650-403e-bc81-4f6e5678bc0e"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "configparser.NoOptionError: No option 'uri' in section: 'URLs'\n", "trace": "  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\tests\\base.py\", line 15, in setup\n    uri = config_reader.get_URI()\n  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\configs\\config.py\", line 39, in get_URI\n    return self.get_value('URLs', 'URI')\n  File \"E:\\PythonFramework\\PythonPyTestFrameWorkAPI\\configs\\config.py\", line 23, in get_value\n    return self.config.get(section, key)\n  File \"C:\\python\\lib\\configparser.py\", line 793, in get\n    raise NoOptionError(option, section)\n"}, "start": 1694173608268, "stop": 1694173608268}], "start": 1694173608268, "stop": 1694173608378}